In [1]:
# Carregando minhas biblotecas
import pandas as pd
import numpy as np

In [2]:
# Importando nossa Biblioteca Scikit Learn com nosso pacote OneHotEnconder

# para transformar nossas variaveis
from sklearn.preprocessing import OneHotEncoder

# Aplica transformadores a colunas de um array ou DataFrame do pandas.
from sklearn.compose import ColumnTransformer

# Importando nossa biblioteca para dividi nossas classes entre treino e teste
from sklearn.model_selection import train_test_split

# Importando nosa biblioteca para o Treinamento do Algortmo
from sklearn.linear_model import LinearRegression

In [3]:
# Carregando meu Dataset
dataset = pd.read_csv("startups.csv")

In [4]:
# Vizualizando meus dados
dataset.head()

Administração   Pesquisa  Propaganda          Estado      Lucro
0      136897.80  165349.20   471784.10          Paraná  192261.83
1      151377.59  162597.70   443898.53       São Paulo  191792.06
2      101145.55  153441.51   407934.54  Rio de Janeiro  191050.39
3      118671.85  144372.41   383199.62          Paraná  182901.99
4       91391.77  142107.34   366168.42  Rio de Janeiro  166187.94

In [5]:
# Indentificacao de nossas variaveis Idependetes e Dependentes

# Outra maneira
# X = dataset.iloc[:, :-1]

# Variavel Independente
X = dataset.iloc[:, 0:4].values

# Variavel Depentente
y = dataset.iloc[:, 4].values

In [9]:
# Vizualizando minha variavel X
X

array([[136897.8, 165349.2, 471784.1, 'Paraná'],
       [151377.59, 162597.7, 443898.53, 'São Paulo'],
       [101145.55, 153441.51, 407934.54, 'Rio de Janeiro'],
       [118671.85, 144372.41, 383199.62, 'Paraná'],
       [91391.77, 142107.34, 366168.42, 'Rio de Janeiro'],
       [99814.71, 131876.9, 362861.36, 'Paraná'],
       [147198.87, 134615.46, 127716.82, 'São Paulo'],
       [145530.06, 130298.13, 323876.68, 'Rio de Janeiro'],
       [148718.95, 120542.52, 311613.29, 'Paraná'],
       [108679.17, 123334.88, 304981.62, 'São Paulo'],
       [110594.11, 101913.08, 229160.95, 'Rio de Janeiro'],
       [91790.61, 100671.96, 249744.55, 'São Paulo'],
       [127320.38, 93863.75, 249839.44, 'Rio de Janeiro'],
       [135495.07, 91992.39, 252664.93, 'São Paulo'],
       [156547.42, 119943.24, 256512.92, 'Rio de Janeiro'],
       [122616.84, 114523.61, 261776.23, 'Paraná'],
       [121597.55, 78013.11, 264346.06, 'São Paulo'],
       [145077.58, 94657.16, 282574.31, 'Paraná'],
       [11

In [10]:
# Vizualizando minha variavel y
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [11]:
# Iremos agora Codificar nossa Variavel Categorica Estado

# Ao especificar remainder='passthrough',
# todas as colunas restantes que não foram especificadas
# em transformers, mas presentes nos dados passados ​​para fit serão
# passadas automaticamente

coluna_transformada = ColumnTransformer([('enconder', OneHotEncoder(),[3])],
                                        remainder ='passthrough')

In [14]:
# Transformando minha variaveis Independentes

# Podmeos verificar que foi removido a coluna Estado criando as colunas
# 0,1 e 2 cada um com uma variavel fecticia indicado a qual estado aquela
# Standarp pertence

X = np.array(coluna_transformada.fit_transform(X), dtype = np.float64)

In [15]:
# Evitando nossa Armadilha Ficticia excluindo nossa coluna 0
X = X[:,1:]

In [16]:
# Fazendo nossa Divisão da amostra com nossa verificação Cruzada
# cross-validation, sendo nossa divisão de treinamento e teste 80% dos dados

# 80% treino (0,8 * 50 = 40 amostras)
# 20% teste  (0,2 * 50, = 10 amostras)

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state= 0)

In [17]:
# Treinamento de Nosso Algoritmo

# Criando nosso regressor
regressor = LinearRegression()

In [18]:
# Fazendo nosso treinamento lembrando sempre com nossas variaveis de Treino
regressor.fit(X_train,y_train)

LinearRegression()

In [19]:
# Fazendo agora nossa Predição do Algoritmo

# Lembrando que preveremos com os dados de treino e assim passando nossos
# dados reais

y_pred = regressor.predict(X_test)

In [20]:
# Criando um Loop for para comparar os valores
for k in range(len(y_test)):
    y_teste = y_test[k]
    y_previsto = y_pred[k]
    erro = abs((y_test[k] - y_pred[k])/ y_pred[k] *100)
    print(f'y_teste: {y_teste:.2f} y_previsto: {y_previsto:.2f} erro: {erro:.2f}')

y_teste: 103282.38 y_previsto: 103015.20 erro: 0.26
y_teste: 144259.40 y_previsto: 132582.28 erro: 8.81
y_teste: 146121.95 y_previsto: 132447.74 erro: 10.32
y_teste: 77798.83 y_previsto: 71976.10 erro: 8.09
y_teste: 191050.39 y_previsto: 178537.48 erro: 7.01
y_teste: 105008.31 y_previsto: 116161.24 erro: 9.60
y_teste: 81229.06 y_previsto: 67851.69 erro: 19.72
y_teste: 97483.56 y_previsto: 98791.73 erro: 1.32
y_teste: 110352.25 y_previsto: 113969.44 erro: 3.17
y_teste: 166187.94 y_previsto: 167921.07 erro: 1.03


In [21]:
#  Verificando nosso P-values (Quanto menor mais significativo)

# Verificando a significancia estatistica das variaveis

# Importando nossa Biblioteca
import statsmodels.api as sm

In [22]:
# Criando minha variavel com minhas colunas
X_opt = X[:,[0,1,2,3,4]]


In [23]:
# Criando meu Regressor e fazendo meu treinamento
regressor_OLS = sm.OLS(y, X_opt).fit()

In [24]:
# Verificando minhas estatistica
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.988
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              735.7
Date:                Fri, 29 Mar 2024   Prob (F-statistic):                    6.07e-42
Time:                        14:14:50   Log-Likelihood:                         -544.86
No. Observations:                  50   AIC:                                      1100.
Df Residuals:                      45   BIC:                                      1109.
Df Model:                           5                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          3814.3461   4819.854      0.791      0.433   -5893.338    1.35e+04
x2          6019.9282   4596.090      1.310      0.197   -3237.072    1.53e+04
x3             0.3021      0.037      8.174      0.000       0.228       0.377
x4             0.7308      0.066     11.072      0.000       0.598       0.864
x5             0.0776      0.023      3.397      0.001       0.032       0.124
==============================================================================
Omnibus:                        0.012   Durbin-Watson:                   1.533
Prob(Omnibus):                  0.994   Jarque-Bera (JB):                0.071
Skew:                          -0.015   Prob(JB):                        0.965
Kurtosis:                       2.817   Cond. No.                     8.14e+05
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 8.14e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [25]:
# Verificando agora apenas com as colunas "Pesquisa,ropaganda e Estado

# Criando minha variavel com minhas colunas
X_opt = X[:,[2,3,4]]


In [26]:
# Criando meu Regressor e fazendo meu treinamento
regressor_OLS = sm.OLS(y, X_opt).fit()

In [27]:
# Verificando minhas estatistica
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              1232.
Date:                Fri, 29 Mar 2024   Prob (F-statistic):                    1.17e-44
Time:                        14:15:39   Log-Likelihood:                         -545.82
No. Observations:                  50   AIC:                                      1098.
Df Residuals:                      47   BIC:                                      1103.
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.3277      0.031     10.458      0.000       0.265       0.391
x2             0.7180      0.065     11.047      0.000       0.587       0.849
x3             0.0822      0.022      3.733      0.001       0.038       0.126
==============================================================================
Omnibus:                        0.665   Durbin-Watson:                   1.361
Prob(Omnibus):                  0.717   Jarque-Bera (JB):                0.749
Skew:                          -0.126   Prob(JB):                        0.688
Kurtosis:                       2.456   Cond. No.                         9.76
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
# Verificando agora apenas com as colunas "Pesquisa e Propaganda"

# Criando minha variavel com minhas colunas
X_opt = X[:,[2,3]]

In [29]:
# Criando meu Regressor e fazendo meu treinamento
regressor_OLS = sm.OLS(y, X_opt).fit()

In [30]:
# Verificando minhas estatistica
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.984
Model:                            OLS   Adj. R-squared (uncentered):              0.983
Method:                 Least Squares   F-statistic:                              1450.
Date:                Fri, 29 Mar 2024   Prob (F-statistic):                    1.20e-43
Time:                        14:16:06   Log-Likelihood:                         -552.31
No. Observations:                  50   AIC:                                      1109.
Df Residuals:                      48   BIC:                                      1112.
Df Model:                           2                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.3558      0.034     10.381      0.000       0.287       0.425
x2             0.8974      0.049     18.219      0.000       0.798       0.996
==============================================================================
Omnibus:                        0.094   Durbin-Watson:                   1.153
Prob(Omnibus):                  0.954   Jarque-Bera (JB):                0.287
Skew:                           0.052   Prob(JB):                        0.866
Kurtosis:                       2.643   Cond. No.                         3.90
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [31]:
# Verificando meus Pvalores
regressor_OLS.pvalues

array([7.33006903e-14, 3.33897094e-23])

# Esses resultados mostram que a coluna "Pesquisa", tem mais impacto como nossa coluna Lucro sendo ela mais impactante para os resultados

# array([7.33006903e-14, 3.33897094e-23])

